import { existsSync, readFileSync } from "node:fs";
import { join, posix } from "node:path";
import { describe, expect, it } from "vitest";
import { REPO_ROOT, packageReadmes, sweptDocs } from "./doc-sweep.js";

/**
 * LINK-fmmzkmas — every repo-relative markdown link in the swept prose resolves
 * to a path that exists.
 *
 * `pnpm check` is build + typecheck + vitest + cucumber, and until this file
 * NOTHING in it verified that an intra-repo link resolves. Cross-document links
 * were verified by hand at authoring time and were unpinned from the moment
 * they landed.
 *
 * The rot is measured, not hypothetical. The content pass that added those
 * links existed BECAUSE citations had already rotted: three corpus line
 * references pointed at the wrong rows, one of them into a row carrying the
 * OPPOSITE label. `LINK-hmvdnyds` carried four rotted citations, all
 * load-bearing in a verdict that had to be withdrawn. Citations in this
 * repository rot on a timescale of weeks.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT THIS DOES NOT CATCH. A LINK CHECKER IS A FLOOR, NOT A CEILING.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * This asserts that a path EXISTS. It says nothing about whether the thing at
 * that path is what the sentence claims. That is the failure mode that actually
 * bit: `corpus.ts:449` existed — it simply described a different URL, with the
 * opposite label, because rows had been inserted above it. A green run here is
 * consistent with every citation in the repository pointing at the wrong
 * content.
 *
 * Line-number citations are the rot-prone form: they break silently on any edit
 * above them and no mechanical check can notice. The durable fix is not a
 * better link checker, it is anchoring citations on things that move WITH what
 * they name — a symbol, an exact quoted string, a date, a reason code — so that
 * a stale citation fails to resolve at all rather than resolving to a lie.
 * Prefer that form when writing. Do not read a green suite here as evidence
 * that a citation is accurate; it is evidence only that a file is still there.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * ANCHOR FRAGMENTS (`#section`) ARE DELIBERATELY NOT CHECKED.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * The path half of `foo.md#bar` IS checked; the `#bar` half is not, and that is
 * a decision rather than an omission. Heading anchors are not a property of the
 * markdown — they are generated by whichever renderer displays it, and the two
 * renderers this repository is read through do not agree. Both spellings are
 * present in the tree today, on headings of identical shape:
 *
 *   README.md → `docs/scoring.md#gating-on-results--status-invalid-…`
 *     for the heading `### Gating on results — \`status: "invalid"\` …`
 *     (em dash deleted, the spaces around it left behind → DOUBLE hyphen)
 *
 *   README.md → `#mcp-server-check-before-you-fetch`
 *     for the heading `## MCP server — check before you fetch`
 *     (same shape, repeated hyphens collapsed → SINGLE hyphen)
 *
 * No single slugifier makes both green. A fragment check would therefore have
 * to pick a renderer and land RED on prose that is correct for the other one —
 * a guard that fails on correct input is worse than no guard, because the fix
 * people reach for is to delete it. Checking fragments is a real second step,
 * but it needs a prior decision about which renderer is canonical and a pass to
 * make the existing fragments consistent with it. Both are out of scope here
 * and neither is blocked by this file. See the report on LINK-fmmzkmas.
 */

/**
 * The files whose links are checked: the recursive `docs/` sweep, the root
 * README, and every package README — the same walk the claim budget uses, from
 * `./doc-sweep.ts`, so the two guards cannot drift apart.
 *
 * `docs/guarantees.md` IS included here. The register exempts itself from its
 * own CLAIM BUDGET because it quotes the claims it tracks; that exemption has
 * nothing to do with whether its links resolve.
 */
function linkedFiles(): string[] {
  return [...sweptDocs(join(REPO_ROOT, "docs")), "README.md", ...packageReadmes(REPO_ROOT)];
}

/**
 * Inline markdown links and images: `[text](target)`, `![alt](target)`,
 * optionally with a `"title"`. The link text may itself contain one bracket
 * pair (`[\`foo\`](x)` after code-span stripping, or a nested `[§4]`), which
 * the inner alternation allows.
 *
 * Reference-style definitions (`[label]: target`) and raw HTML `<a href>` are
 * NOT matched, because neither form appears anywhere in the swept set — see the
 * "no unmatched link form has crept in" assertion below, which reddens if one
 * ever does rather than letting it slip past unchecked.
 */
const INLINE_LINK = /\[(?:[^\][]|\[[^\][]*\])*\]\(\s*([^)\s]+?)\s*(?:\s+"[^"]*")?\)/g;
const FENCE = /^(?:```|~~~)/;

/**
 * Blank out fenced code blocks and inline code spans, preserving line count so
 * reported line numbers stay true. A link inside a code sample is an example,
 * not a citation, and asserting it would redden on documentation that is
 * working as intended.
 */
function strippedOfCode(markdown: string): string {
  let inFence = false;
  return markdown
    .split("\n")
    .map((line) => {
      if (FENCE.test(line.trim())) {
        inFence = !inFence;
        return "";
      }
      if (inFence) return "";
      // Code spans go last so `[\`docs/x.md\`](../x.md)` keeps its link: only
      // the backticks inside the link TEXT are removed, not the brackets.
      return line.replace(/`[^`]*`/g, (span) => " ".repeat(span.length));
    })
    .join("\n");
}

interface DocLink {
  /** Repo-relative path of the file the link was written in. */
  readonly file: string;
  /** Exactly as written, e.g. `../packages/core/README.md#usage`. */
  readonly target: string;
  /** 1-based line of the start of the link, for the failure message. */
  readonly line: number;
}

function linksIn(file: string): DocLink[] {
  const text = strippedOfCode(readFileSync(join(REPO_ROOT, file), "utf8"));
  return [...text.matchAll(INLINE_LINK)].map((match) => ({
    file,
    target: match[1] as string,
    line: text.slice(0, match.index).split("\n").length,
  }));
}

/**
 * A target is out of scope when it names somewhere other than a path in this
 * repository: any absolute URL (`https:`, `mailto:`, …), a protocol-relative
 * `//host/…`, or a bare `#fragment` into the current document. Everything else
 * is a repo-relative path and must exist.
 */
function isRepoRelative(target: string): boolean {
  return !/^[a-z][a-z0-9+.-]*:/i.test(target) && !target.startsWith("//") && !target.startsWith("#");
}

/** Resolve a repo-relative target against the linking file. Fragment dropped. */
function resolveTarget(file: string, target: string): string {
  const hash = target.indexOf("#");
  const path = hash < 0 ? target : target.slice(0, hash);
  return posix.normalize(posix.join(posix.dirname(file), path));
}

const files = linkedFiles();
const allLinks = files.flatMap(linksIn);
const repoLinks = allLinks.filter((link) => isRepoRelative(link.target));

describe("intra-repo markdown links resolve (LINK-fmmzkmas)", () => {
  it("finds prose and links at all (guards against a silently empty sweep)", () => {
    // Every one of these floors was met with room to spare when written
    // (28 files, 100+ links, 84 of them repo-relative). They exist so that a
    // regression in the walk, the code stripping, or the link regex reddens
    // here instead of turning the whole guard into a vacuous pass.
    expect(files.length).toBeGreaterThan(20);
    expect(files).toContain("README.md");
    expect(files).toContain("docs/guarantees.md");
    expect(allLinks.length).toBeGreaterThan(60);
    expect(repoLinks.length).toBeGreaterThan(50);
    expect(allLinks.length).toBeGreaterThan(repoLinks.length); // external links exist too
  });

  it.each(repoLinks.map((link) => [`${link.file}:${link.line} → ${link.target}`, link] as const))(
    "%s exists",
    (_label, link) => {
      const resolved = resolveTarget(link.file, link.target);
      expect(
        existsSync(join(REPO_ROOT, resolved)),
        `${link.file}:${link.line} links to \`${link.target}\`, which resolves to ` +
          `\`${resolved}\` — and nothing is there. Fix the link or restore the target. ` +
          "If the target moved, prefer re-anchoring the citation on a symbol or an " +
          "exact quoted string rather than on a path plus a line number.",
      ).toBe(true);
    },
  );

  it("no unmatched link form has crept in", () => {
    // `INLINE_LINK` only understands inline links. If someone introduces a
    // reference-style definition or a raw `<a href>`, its target would be
    // checked by nobody — so fail here and widen the parser deliberately,
    // rather than growing a silent blind spot inside the guard.
    const offenders = files.flatMap((file) => {
      const text = strippedOfCode(readFileSync(join(REPO_ROOT, file), "utf8"));
      const reference = /^\s{0,3}\[[^\][]+\]:\s*\S/m.test(text);
      const html = /<a\s[^>]*href=|<img\s[^>]*src=/i.test(text);
      return reference || html ? [file] : [];
    });
    expect(
      offenders,
      `${offenders.join(", ")} uses a link form this test does not parse ` +
        "(reference-style definition or raw HTML). Teach INLINE_LINK about it, " +
        "or the target goes unchecked.",
    ).toEqual([]);
  });
});

/**
 * The guard, pinned against inputs whose right answer is known — so that a
 * regression turns this red rather than quietly classifying every link as "out
 * of scope" and passing on an empty set.
 */
describe("link classification and resolution (LINK-fmmzkmas)", () => {
  it.each([
    ["https://example.com/x", false],
    ["HTTPS://EXAMPLE.COM", false],
    ["mailto:security@example.com", false],
    ["//cdn.example.com/x.png", false],
    ["#a-heading-in-this-file", false],
    ["architecture.md", true],
    ["./worklog-pblqdrco-digits-in-labels.md", true],
    ["../packages/core/README.md", true],
    ["docs/scoring.md#gating-on-results", true],
  ])("%s is repo-relative: %s", (target, expected) => {
    expect(isRepoRelative(target)).toBe(expected);
  });

  it.each([
    ["docs/architecture.md", "enforcement.md", "docs/enforcement.md"],
    ["docs/architecture.md", "./enforcement.md", "docs/enforcement.md"],
    ["docs/bundle-size-budget.md", "../packages/core/x.ts", "packages/core/x.ts"],
    ["README.md", "./docs/scoring.md", "docs/scoring.md"],
    ["packages/core/README.md", "../../docs/scoring.md", "docs/scoring.md"],
    ["README.md", "docs/scoring.md#gating-on-results", "docs/scoring.md"],
  ])("%s + %s → %s", (file, target, expected) => {
    expect(resolveTarget(file, target)).toBe(expected);
  });

  it("a link to a path that is not there is REPORTED MISSING, not skipped", () => {
    // The whole guard reduces to this one call. If `existsSync` were ever fed a
    // path that silently resolves (a stray join against cwd, say), everything
    // above would pass on nonsense.
    const resolved = resolveTarget("docs/architecture.md", "./no-such-worklog.md");
    expect(resolved).toBe("docs/no-such-worklog.md");
    expect(existsSync(join(REPO_ROOT, resolved))).toBe(false);
  });

  it("links inside fenced blocks and code spans are not citations", () => {
    const sample = ["Real [a](./real.md).", "```md", "[b](./fenced.md)", "```", "`[c](./span.md)`"]
      .join("\n")
      .concat("\n");
    const targets = [...strippedOfCode(sample).matchAll(INLINE_LINK)].map((m) => m[1]);
    expect(targets).toEqual(["./real.md"]);
  });
});
