import { existsSync, readFileSync } from "node:fs";
import { join, posix } from "node:path";
import { describe, expect, it } from "vitest";
import { REPO_ROOT, packageReadmes, sweptDocs } from "./doc-sweep.js";

/**
 * LINK-fmmzkmas — every repo-relative markdown link in the swept prose resolves
 * to a path that exists.
 *
 * `pnpm check` is build + typecheck + vitest + cucumber, and until this file
 * NOTHING in it verified that an intra-repo link resolves. Cross-document links
 * were verified by hand at authoring time and were unpinned from the moment
 * they landed.
 *
 * The rot is measured, not hypothetical. The content pass that added those
 * links existed BECAUSE citations had already rotted: three corpus line
 * references pointed at the wrong rows, one of them into a row carrying the
 * OPPOSITE label. `LINK-hmvdnyds` carried four rotted citations, all
 * load-bearing in a verdict that had to be withdrawn. Citations in this
 * repository rot on a timescale of weeks.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT THIS DOES NOT CATCH. A LINK CHECKER IS A FLOOR, NOT A CEILING.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * This asserts that a path EXISTS. It says nothing about whether the thing at
 * that path is what the sentence claims. That is the failure mode that actually
 * bit: `corpus.ts:449` existed — it simply described a different URL, with the
 * opposite label, because rows had been inserted above it. A green run here is
 * consistent with every citation in the repository pointing at the wrong
 * content.
 *
 * Line-number citations are the rot-prone form: they break silently on any edit
 * above them and no mechanical check can notice. The durable fix is not a
 * better link checker, it is anchoring citations on things that move WITH what
 * they name — a symbol, an exact quoted string, a date, a reason code — so that
 * a stale citation fails to resolve at all rather than resolving to a lie.
 * Prefer that form when writing. Do not read a green suite here as evidence
 * that a citation is accurate; it is evidence only that a file is still there.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * ANCHOR FRAGMENTS (`#section`) ARE CHECKED, AGAINST GITLAB (LINK-quzdwhjt).
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * LINK-fmmzkmas checked the path half of `foo.md#bar` and deliberately left the
 * `#bar` half alone, because heading anchors are not a property of the markdown
 * — they are generated by whichever renderer displays it — and the tree carried
 * BOTH spellings on headings of identical shape: `docs/scoring.md#gating-on-
 * results--status-invalid-…` kept the two spaces a deleted em dash left behind
 * as a DOUBLE hyphen, while `#mcp-server-check-before-you-fetch` collapsed them
 * to a SINGLE one. No slugifier makes both green, so one was already dead, and
 * a check that picked wrong would redden on prose that was right — the kind of
 * guard people delete. The missing prerequisite was a decision about which
 * renderer is canonical.
 *
 * That is now settled by MEASUREMENT rather than by argument. GitLab is where
 * this repository's docs are read; the GitHub account is dead and its artifacts
 * were retired. GitLab's blob view is a client-side shell, but the same URL
 * with `?format=json&viewer=rich` returns the server-rendered markdown, so its
 * ids can simply be read off:
 *
 *   README.md         → id="user-content-mcp-server--check-before-you-fetch"
 *                       and the heading's own self-link,
 *                       href="#mcp-server--check-before-you-fetch"
 *   docs/scoring.md   → id="user-content-gating-on-results--status-invalid-
 *                       must-be-handled-explicitly"
 *
 * GitLab does NOT squeeze repeated hyphens. The `docs/scoring.md` link was
 * right; the MCP one was the dead one, and it is fixed. `gitlabAnchor()` below
 * was then derived from — not assumed and spot-checked against — the rendered
 * ids of ALL 321 headings across all 29 markdown files in this repository,
 * fetched in one pass on 2026-09-05. It reproduces 321/321 exactly, and the
 * heading EXTRACTOR reproduces GitLab's heading set file-for-file (no setext
 * headings exist here, and `#` lines inside fences are correctly not headings).
 *
 * Two branches of the algorithm are NOT evidenced by this tree — it contains no
 * duplicate heading slugs and no digits-only heading — so they are admitted
 * PERMISSIVELY rather than guessed at strictly; see `anchorsIn()`. A guard that
 * reddens on correct prose is the failure mode this whole check was deferred to
 * avoid, and it is not worth reintroducing for a case nobody has written.
 *
 * SWEEP BOUNDARY, INHERITED. Fragments are checked in the files `linkedFiles()`
 * sweeps, which is the claim budget's walk (see `./doc-sweep.ts` for why the
 * two must not diverge). Anchors are RESOLVED in whatever file a link names, so
 * targets outside the sweep — `SECURITY.md#scope`, `CONTRIBUTING.md#the-verify-
 * gate` — are checked as targets. Links written IN an unswept file are not; all
 * four such fragments (`CONTRIBUTING.md`, `SECURITY.md`, `tools/README.md` ×2)
 * were verified by hand against the same rendered ids under LINK-quzdwhjt.
 */

/**
 * The files whose links are checked: the recursive `docs/` sweep, the root
 * README, and every package README — the same walk the claim budget uses, from
 * `./doc-sweep.ts`, so the two guards cannot drift apart.
 *
 * `docs/guarantees.md` IS included here. The register exempts itself from its
 * own CLAIM BUDGET because it quotes the claims it tracks; that exemption has
 * nothing to do with whether its links resolve.
 */
function linkedFiles(): string[] {
  return [...sweptDocs(join(REPO_ROOT, "docs")), "README.md", ...packageReadmes(REPO_ROOT)];
}

/**
 * Inline markdown links and images: `[text](target)`, `![alt](target)`,
 * optionally with a `"title"`. The link text may itself contain one bracket
 * pair (`[\`foo\`](x)` after code-span stripping, or a nested `[§4]`), which
 * the inner alternation allows.
 *
 * Reference-style definitions (`[label]: target`) and raw HTML `<a href>` are
 * NOT matched, because neither form appears anywhere in the swept set — see the
 * "no unmatched link form has crept in" assertion below, which reddens if one
 * ever does rather than letting it slip past unchecked.
 */
const INLINE_LINK = /\[(?:[^\][]|\[[^\][]*\])*\]\(\s*([^)\s]+?)\s*(?:\s+"[^"]*")?\)/g;
const FENCE = /^(?:```|~~~)/;

/**
 * Blank out fenced code blocks and inline code spans, preserving line count so
 * reported line numbers stay true. A link inside a code sample is an example,
 * not a citation, and asserting it would redden on documentation that is
 * working as intended.
 */
function strippedOfCode(markdown: string): string {
  let inFence = false;
  return markdown
    .split("\n")
    .map((line) => {
      if (FENCE.test(line.trim())) {
        inFence = !inFence;
        return "";
      }
      if (inFence) return "";
      // Code spans go last so `[\`docs/x.md\`](../x.md)` keeps its link: only
      // the backticks inside the link TEXT are removed, not the brackets.
      return line.replace(/`[^`]*`/g, (span) => " ".repeat(span.length));
    })
    .join("\n");
}

interface DocLink {
  /** Repo-relative path of the file the link was written in. */
  readonly file: string;
  /** Exactly as written, e.g. `../packages/core/README.md#usage`. */
  readonly target: string;
  /** 1-based line of the start of the link, for the failure message. */
  readonly line: number;
}

function linksIn(file: string): DocLink[] {
  const text = strippedOfCode(readFileSync(join(REPO_ROOT, file), "utf8"));
  return [...text.matchAll(INLINE_LINK)].map((match) => ({
    file,
    target: match[1] as string,
    line: text.slice(0, match.index).split("\n").length,
  }));
}

/**
 * A target is out of scope when it names somewhere other than a path in this
 * repository: any absolute URL (`https:`, `mailto:`, …), a protocol-relative
 * `//host/…`, or a bare `#fragment` into the current document. Everything else
 * is a repo-relative path and must exist.
 */
function isRepoRelative(target: string): boolean {
  return !/^[a-z][a-z0-9+.-]*:/i.test(target) && !target.startsWith("//") && !target.startsWith("#");
}

/** Resolve a repo-relative target against the linking file. Fragment dropped. */
function resolveTarget(file: string, target: string): string {
  const hash = target.indexOf("#");
  const path = hash < 0 ? target : target.slice(0, hash);
  return posix.normalize(posix.join(posix.dirname(file), path));
}

/**
 * GitLab's heading-anchor algorithm, derived from its rendered output.
 *
 * Everything outside `\p{L}\p{M}\p{N}\p{Pc}`, space and `-` is DELETED (not
 * replaced), spaces then become hyphens, and repeated hyphens SURVIVE — which
 * is the whole point: an em dash surrounded by spaces leaves two of them.
 *
 * `\p{M}` is load-bearing and is why this cannot be spelled `\w`. `İ`
 * (U+0130) lowercases to `i` + U+0307 COMBINING DOT ABOVE; U+0307 is a mark,
 * which GitLab keeps and `\w` would drop. `docs/locale-case-mapping.md` has
 * exactly that heading, and it is pinned below.
 */
const NON_ANCHOR = /[^\p{L}\p{M}\p{N}\p{Pc} -]/gu;

export function gitlabAnchor(headingText: string): string {
  const slug = headingText.trim().toLowerCase().replace(NON_ANCHOR, "").replaceAll(" ", "-");
  // Digits-only: unevidenced here (no such heading exists), see `anchorsIn`.
  return /^\d+$/.test(slug) ? `anchor-${slug}` : slug;
}

const ATX_HEADING = /^#{1,6}\s/;

/**
 * The rendered text content of an ATX heading line — what `gitlabAnchor` is fed.
 *
 * GitLab slugifies the heading's TEXT, so inline markup contributes its
 * contents, not its syntax: `` `status: "invalid"` `` contributes
 * `status: "invalid"`. Only the four inline forms that actually occur in this
 * repository's 321 headings are handled — code spans (86), strong (4),
 * emphasis (4), and links (0, handled anyway because they are the form most
 * likely to be written next). Verified to reproduce GitLab's rendered text for
 * all 321.
 */
export function headingText(line: string): string {
  return line
    .replace(/^#+[ \t]*/, "")
    .replace(/\s+#+\s*$/, "") // CommonMark closing sequence, space-preceded
    .replace(/!?\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/`/g, "")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/(?<!\w)_([^_]+)_(?!\w)/g, "$1")
    .trim();
}

/**
 * Every fragment `file` offers, as a set.
 *
 * Headings inside fenced code blocks are samples, not headings — the same rule
 * `strippedOfCode` applies to links — so the fence state is tracked here too.
 *
 * PERMISSIVE ON THE TWO UNEVIDENCED BRANCHES. This repository has no duplicate
 * heading slug and no digits-only heading, so GitLab's disambiguation suffix
 * and its digits-only prefix were never observed in the fetched output and are
 * not asserted. A repeated slug therefore also admits `slug-1`…`slug-(n-1)`,
 * and a digits-only heading admits both spellings. Being wrong in this
 * direction lets one hypothetical bad link through; being wrong in the other
 * reddens correct prose, which is what got fragment checking deferred once.
 */
function anchorsIn(file: string): Set<string> {
  const anchors = new Set<string>();
  const counts = new Map<string, number>();
  let inFence = false;
  for (const line of readFileSync(join(REPO_ROOT, file), "utf8").split("\n")) {
    if (FENCE.test(line.trim())) {
      inFence = !inFence;
      continue;
    }
    if (inFence || !ATX_HEADING.test(line)) continue;
    const text = headingText(line);
    const base = gitlabAnchor(text);
    const seen = counts.get(base) ?? 0;
    counts.set(base, seen + 1);
    anchors.add(base);
    if (seen > 0) anchors.add(`${base}-${seen}`);
    if (base.startsWith("anchor-")) anchors.add(base.slice("anchor-".length));
  }
  return anchors;
}

interface FragmentRef {
  /** Repo-relative path of the document the fragment must exist in. */
  readonly file: string;
  /** The `#`-less fragment, exactly as written. */
  readonly fragment: string;
}

/**
 * The fragment a link names, or `null` if it names none.
 *
 * Deliberately NOT `isRepoRelative`: that classifier sends a bare `#section`
 * out of scope, because it resolves to no path — but a bare `#section` is
 * precisely an anchor into the current document, and README.md:55 (the dead
 * one) was exactly that form.
 */
function fragmentRef(link: DocLink): FragmentRef | null {
  if (/^[a-z][a-z0-9+.-]*:/i.test(link.target) || link.target.startsWith("//")) return null;
  const hash = link.target.indexOf("#");
  if (hash < 0) return null;
  const fragment = link.target.slice(hash + 1);
  if (fragment === "") return null;
  const file = hash === 0 ? link.file : resolveTarget(link.file, link.target);
  return { file, fragment };
}

const files = linkedFiles();
const allLinks = files.flatMap(linksIn);
const repoLinks = allLinks.filter((link) => isRepoRelative(link.target));

/** Fragment links whose target document exists — a missing path is the path test's. */
const fragmentLinks = allLinks.flatMap((link) => {
  const ref = fragmentRef(link);
  return ref && existsSync(join(REPO_ROOT, ref.file)) ? [{ link, ref } as const] : [];
});

describe("intra-repo markdown links resolve (LINK-fmmzkmas)", () => {
  it("finds prose and links at all (guards against a silently empty sweep)", () => {
    // Every one of these floors was met with room to spare when written
    // (28 files, 100+ links, 84 of them repo-relative). They exist so that a
    // regression in the walk, the code stripping, or the link regex reddens
    // here instead of turning the whole guard into a vacuous pass.
    expect(files.length).toBeGreaterThan(20);
    expect(files).toContain("README.md");
    expect(files).toContain("docs/guarantees.md");
    expect(allLinks.length).toBeGreaterThan(60);
    expect(repoLinks.length).toBeGreaterThan(50);
    expect(allLinks.length).toBeGreaterThan(repoLinks.length); // external links exist too
  });

  it.each(repoLinks.map((link) => [`${link.file}:${link.line} → ${link.target}`, link] as const))(
    "%s exists",
    (_label, link) => {
      const resolved = resolveTarget(link.file, link.target);
      expect(
        existsSync(join(REPO_ROOT, resolved)),
        `${link.file}:${link.line} links to \`${link.target}\`, which resolves to ` +
          `\`${resolved}\` — and nothing is there. Fix the link or restore the target. ` +
          "If the target moved, prefer re-anchoring the citation on a symbol or an " +
          "exact quoted string rather than on a path plus a line number.",
      ).toBe(true);
    },
  );

  it.each(
    fragmentLinks.map(
      ({ link, ref }) => [`${link.file}:${link.line} → ${link.target}`, link, ref] as const,
    ),
  )("%s resolves to a heading", (_label, link, ref) => {
    const anchors = anchorsIn(ref.file);
    const collapsed = new Map(
      [...anchors].map((anchor) => [anchor.replace(/-+/g, "-"), anchor] as const),
    );
    const nearMiss = collapsed.get(ref.fragment.replace(/-+/g, "-"));
    expect(
      anchors.has(ref.fragment),
      `${link.file}:${link.line} links to \`${link.target}\`, but \`${ref.file}\` has no ` +
        `heading GitLab renders as \`#${ref.fragment}\`.` +
        (nearMiss && nearMiss !== ref.fragment
          ? ` Did you mean \`#${nearMiss}\`? GitLab does NOT squeeze repeated hyphens — an ` +
            "em dash between spaces leaves TWO."
          : " Fix the fragment or restore the heading."),
    ).toBe(true);
  });

  it("finds fragments and headings at all (guards against a vacuous fragment check)", () => {
    // Both floors were met with room to spare when written: 7 fragment links in
    // the swept set, and 321 headings across the repository. They exist so that
    // a regression in `fragmentRef`, `anchorsIn` or the heading regex reddens
    // here rather than turning the fragment check into a pass over nothing.
    expect(fragmentLinks.length).toBeGreaterThan(4);
    expect(anchorsIn("README.md").size).toBeGreaterThan(15);
    // The two anchors that were in conflict, now both GitLab-correct.
    expect(anchorsIn("README.md")).toContain("mcp-server--check-before-you-fetch");
    expect(anchorsIn("docs/scoring.md")).toContain(
      "gating-on-results--status-invalid-must-be-handled-explicitly",
    );
  });

  it("no unmatched link form has crept in", () => {
    // `INLINE_LINK` only understands inline links. If someone introduces a
    // reference-style definition or a raw `<a href>`, its target would be
    // checked by nobody — so fail here and widen the parser deliberately,
    // rather than growing a silent blind spot inside the guard.
    const offenders = files.flatMap((file) => {
      const text = strippedOfCode(readFileSync(join(REPO_ROOT, file), "utf8"));
      const reference = /^\s{0,3}\[[^\][]+\]:\s*\S/m.test(text);
      const html = /<a\s[^>]*href=|<img\s[^>]*src=/i.test(text);
      return reference || html ? [file] : [];
    });
    expect(
      offenders,
      `${offenders.join(", ")} uses a link form this test does not parse ` +
        "(reference-style definition or raw HTML). Teach INLINE_LINK about it, " +
        "or the target goes unchecked.",
    ).toEqual([]);
  });
});

/**
 * The guard, pinned against inputs whose right answer is known — so that a
 * regression turns this red rather than quietly classifying every link as "out
 * of scope" and passing on an empty set.
 */
describe("link classification and resolution (LINK-fmmzkmas)", () => {
  it.each([
    ["https://example.com/x", false],
    ["HTTPS://EXAMPLE.COM", false],
    ["mailto:security@example.com", false],
    ["//cdn.example.com/x.png", false],
    ["#a-heading-in-this-file", false],
    ["architecture.md", true],
    ["./worklog-pblqdrco-digits-in-labels.md", true],
    ["../packages/core/README.md", true],
    ["docs/scoring.md#gating-on-results", true],
  ])("%s is repo-relative: %s", (target, expected) => {
    expect(isRepoRelative(target)).toBe(expected);
  });

  it.each([
    ["docs/architecture.md", "enforcement.md", "docs/enforcement.md"],
    ["docs/architecture.md", "./enforcement.md", "docs/enforcement.md"],
    ["docs/bundle-size-budget.md", "../packages/core/x.ts", "packages/core/x.ts"],
    ["README.md", "./docs/scoring.md", "docs/scoring.md"],
    ["packages/core/README.md", "../../docs/scoring.md", "docs/scoring.md"],
    ["README.md", "docs/scoring.md#gating-on-results", "docs/scoring.md"],
  ])("%s + %s → %s", (file, target, expected) => {
    expect(resolveTarget(file, target)).toBe(expected);
  });

  it("a link to a path that is not there is REPORTED MISSING, not skipped", () => {
    // The whole guard reduces to this one call. If `existsSync` were ever fed a
    // path that silently resolves (a stray join against cwd, say), everything
    // above would pass on nonsense.
    const resolved = resolveTarget("docs/architecture.md", "./no-such-worklog.md");
    expect(resolved).toBe("docs/no-such-worklog.md");
    expect(existsSync(join(REPO_ROOT, resolved))).toBe(false);
  });

  it("links inside fenced blocks and code spans are not citations", () => {
    const sample = ["Real [a](./real.md).", "```md", "[b](./fenced.md)", "```", "`[c](./span.md)`"]
      .join("\n")
      .concat("\n");
    const targets = [...strippedOfCode(sample).matchAll(INLINE_LINK)].map((m) => m[1]);
    expect(targets).toEqual(["./real.md"]);
  });
});

/**
 * `gitlabAnchor` against GitLab's own output (LINK-quzdwhjt).
 *
 * Every expectation below is a TRANSCRIPTION of an `id="user-content-…"` read
 * off GitLab's server-rendered HTML for this repository on 2026-09-05, not a
 * derivation from the implementation. They are the cases that discriminate: if
 * a future edit made the slugifier squeeze hyphens, strip marks, or replace
 * punctuation with a separator instead of deleting it, one of these reddens.
 */
describe("gitlabAnchor matches GitLab's rendered ids (LINK-quzdwhjt)", () => {
  it.each([
    // The two anchors that were in conflict. Repeated hyphens SURVIVE.
    ["MCP server — check before you fetch", "mcp-server--check-before-you-fetch"],
    [
      'Gating on results — status: "invalid" must be handled explicitly',
      "gating-on-results--status-invalid-must-be-handled-explicitly",
    ],
    // `&` is DELETED, not replaced — so `A & B` leaves two hyphens, not three.
    ["Scoring & severity", "scoring--severity"],
    // Section numbers lose their dots and run together: 6.1 → 61.
    ["6.1 PSL snapshot provenance & staleness", "61-psl-snapshot-provenance--staleness"],
    // Apostrophes and quotes vanish with no separator at all: aren't → arent.
    [
      '2. Homographs & confusables — "those letters aren\'t what they look like"',
      "2-homographs--confusables--those-letters-arent-what-they-look-like",
    ],
    // `\p{M}`: İ lowercases to i + U+0307, and GitLab KEEPS the combining mark.
    [
      "D2 — collapse (İ → i): the sharp direction, and it is a real gap",
      "d2--collapse-i̇--i-the-sharp-direction-and-it-is-a-real-gap",
    ],
  ])("%s → %s", (text, expected) => {
    expect(gitlabAnchor(text)).toBe(expected);
  });

  it("does not squeeze repeated hyphens (the decision this unit made)", () => {
    // Stated separately from the table because it is the ONE property that
    // decides which of the two conflicting spellings was correct. GitHub's
    // slugifier collapses here; GitLab's does not, and GitLab is where these
    // docs are read.
    expect(gitlabAnchor("a — b")).toBe("a--b");
    expect(gitlabAnchor("a — b")).not.toBe("a-b");
  });

  it("reads the heading text out of the markdown line, markup and all", () => {
    expect(headingText('### Gating on results — `status: "invalid"` must be handled explicitly')).toBe(
      'Gating on results — status: "invalid" must be handled explicitly',
    );
    expect(headingText("## MCP server — check before you fetch")).toBe(
      "MCP server — check before you fetch",
    );
    expect(headingText("### **Bold** and _thin_ and [linked](./x.md)")).toBe(
      "Bold and thin and linked",
    );
  });

  it("a fragment that names no heading is REPORTED MISSING, not skipped", () => {
    // The fragment half of the guard reduces to this one lookup, exactly as the
    // path half reduces to one `existsSync`. If `anchorsIn` ever returned an
    // empty set for a real file, every fragment above would pass on nonsense.
    const readme = anchorsIn("README.md");
    expect(readme.has("mcp-server--check-before-you-fetch")).toBe(true);
    // The spelling this repository carried until LINK-quzdwhjt. It is dead on
    // GitLab, and the guard must say so.
    expect(readme.has("mcp-server-check-before-you-fetch")).toBe(false);
    expect(readme.has("no-such-heading-anywhere")).toBe(false);
  });

  it("`#` lines inside fenced code blocks are comments, not anchors", () => {
    // `packages/cli/README.md` opens a ```bash fence whose first line is
    // `# annotate a known shortener …` — a shell comment in column 1, which is
    // indistinguishable from an H1 to a regex that does not track fences.
    // GitLab renders no heading there, and neither may this.
    const anchors = anchorsIn("packages/cli/README.md");
    expect(anchors.has("usage")).toBe(true); // a real heading in the same file
    // `# @linklint/cli`: `@` and `/` are deleted with no separator left behind.
    expect(anchors.has("linklintcli")).toBe(true);
    expect(
      anchors.has("annotate-a-known-shortener-without-changing-what-the-score-says-about-it"),
      "a shell comment inside a fence became an anchor — fence tracking is broken, " +
        "and every fragment check downstream is now permissive in a way nobody chose.",
    ).toBe(false);
  });
});
