import type { Detector, DetectorFinding } from "./types.js";
import type { ReasonCode } from "../schema/reason-codes.js";
import { analyzeIpv4, analyzeIpv6 } from "../parse/ip.js";
import {
  CLOUD_METADATA_ENDPOINTS,
  matchCloudMetadataHostname,
  type CloudEndpointKind,
  type CloudMetadataEndpoint,
} from "../data/cloud-metadata.js";
import { matchIpv4Range, matchIpv6Range, type IpRangeBucket } from "../data/ip-ranges.js";

/**
 * Literal-IP range classifier. Informational since LINK-bwqhvjcs: every bucket
 * names the address's destination, not its form, so each emitted code reports at
 * weight 0 (architecture §6.1.10). Classifies a literal IP host into
 * exactly ONE range bucket and emits one reason code naming that bucket. Runs on
 * ALL IP-literal hosts — canonical or obfuscated alike — and reuses the already-
 * decoded canonical/embedded address from `parse/ip.ts` (no IP parsing here).
 *
 * Buckets, most-specific first (emit exactly ONE per address):
 *   ip_cloud_metadata > ip_loopback > ip_link_local > ip_private > ip_reserved
 *
 * The ranges are NOT hand-rolled here. They come from the IANA special-purpose
 * registries (`data/ip-ranges.ts`, generated by tools/build-ip-ranges.mjs) and
 * are matched by LONGEST PREFIX, so an exception inside a block — globally
 * reachable `192.0.0.9/32` inside non-global `192.0.0.0/24` — is expressible.
 * Each matched range carries its registry name and RFC citation into the detail.
 *
 * IPv4-in-IPv6 embeddings (`::ffff:127.0.0.1`) are classified by the EMBEDDED
 * IPv4 — the SSRF masquerade where a validator sees IPv6 but the resolver
 * reaches an internal v4 target. The embedded address is read from the decoded
 * bits of the RFC transition wrapper prefixes, not from the spelling, so the
 * hex form `::ffff:7f00:1` classifies exactly like `::ffff:127.0.0.1`.
 *
 * ONE NON-IP CASE, DELIBERATELY (LINK-hvawpgos). The detector also recognizes
 * the small set of HOSTNAMES a vendor publishes for a metadata endpoint this
 * file already classifies by address (`data/cloud-metadata.ts`,
 * {@link matchCloudMetadataHostname}). Until then `169.254.169.254` scored
 * `high` while `metadata.google.internal` — the same credential endpoint, the
 * spelling Google's own examples use — scored `0.00` with no reasons at all.
 *
 * It rides in THIS detector rather than a new one because the emitted code is
 * unchanged: a matched name is `ip_cloud_metadata`, at the same weight, in the
 * bucket `ip_classification` already declares in `checks.ts`. No new reason
 * code, no registry entry, no schema version.
 *
 * The split it does NOT cross is {@link classifyHost}, which stays IP-only. That
 * function is public API and `@linklint/online` calls it on a RESOLVED address
 * to decide whether a connection may proceed; a hostname branch there would
 * change what a caller outside this package is asking. The name lookup is
 * therefore wired into the detector bodies, and address classification is left
 * exactly as it was.
 */

type Bucket = "ip_cloud_metadata" | IpRangeBucket;

/** A bucket decision, carrying the provider attribution when one applies. */
interface BucketMatch {
  bucket: Bucket;
  /** Cloud vendor owning a matched metadata endpoint; absent for range buckets. */
  provider?: string;
  /** Which flavour of cloud endpoint matched; absent for range buckets. */
  endpointKind?: CloudEndpointKind;
  /** IANA registry name of the matched range; absent for the metadata table. */
  rangeName?: string;
  /** RFC citation of the matched range; absent for the metadata table. */
  rangeRfc?: string;
}

/** Parse a canonical dotted-decimal IPv4 (a.b.c.d) into a 32-bit unsigned int. */
function dottedToInt(dotted: string): number {
  const parts = dotted.split(".");
  let n = 0;
  for (const p of parts) n = n * 256 + Number(p);
  return n >>> 0;
}

/**
 * The curated cloud-metadata table (`data/cloud-metadata.ts`), indexed by the
 * PARSED address so lookups compare decoded bits, never text. Each row is run
 * through the same IPv4/IPv6 parser applied to the host under inspection, so an
 * alternate spelling of a row (`fd00:0ec2::254`) or of the host both collapse to
 * the same key. Built once at module load — per-call cost is one Map lookup.
 *
 * A row that fails to parse is skipped rather than thrown on: `inspect()` must
 * never throw, and importing the library must not fail on a data typo. The
 * table-integrity test asserts every row parses, so a typo fails CI loudly
 * instead of degrading silently at runtime.
 */
const METADATA_IPV4 = new Map<number, CloudMetadataEndpoint>();
const METADATA_IPV6 = new Map<string, CloudMetadataEndpoint>();
for (const endpoint of CLOUD_METADATA_ENDPOINTS) {
  const v4 = analyzeIpv4(endpoint.address);
  if (v4) {
    METADATA_IPV4.set(dottedToInt(v4.canonical), endpoint);
    continue;
  }
  const v6 = analyzeIpv6(endpoint.address);
  if (v6) METADATA_IPV6.set(v6.canonical, endpoint);
}

/**
 * Bucket decision for a matched table row. The bucket — and therefore the
 * emitted reason code — is `ip_cloud_metadata` for EVERY row: the row's `kind`
 * rides along for wording only, so correcting a mis-described endpoint never
 * moves it to a different code (LINK-mjbrzxeo).
 */
function metadataMatch(endpoint: CloudMetadataEndpoint): BucketMatch {
  return {
    bucket: "ip_cloud_metadata",
    provider: endpoint.provider,
    endpointKind: endpoint.kind ?? "instance-metadata",
  };
}

/**
 * Expand an RFC 5952 canonical IPv6 string into its 8 hextets.
 *
 * The input is always the canonical form produced by `parse/ip.ts` (lowercase
 * hex groups, at most one `::`, never a dotted tail), so this is an expansion,
 * not a parse — malformed input simply yields null and the address goes
 * unclassified rather than throwing (`inspect()` must never throw).
 */
function hextetsOf(canonical: string): number[] | null {
  const groups = (s: string): number[] =>
    s === "" ? [] : s.split(":").map((h) => parseInt(h, 16));
  const gap = canonical.indexOf("::");
  let out: number[];
  if (gap < 0) {
    out = groups(canonical);
  } else {
    const left = groups(canonical.slice(0, gap));
    const right = groups(canonical.slice(gap + 2));
    const fill = 8 - left.length - right.length;
    if (fill < 0) return null;
    out = [...left, ...new Array<number>(fill).fill(0), ...right];
  }
  if (out.length !== 8 || out.some((h) => !Number.isInteger(h))) return null;
  return out;
}

/** Classify a canonical dotted-decimal IPv4 into one bucket, or null if public. */
function classifyIpv4(dotted: string): BucketMatch | null {
  const n = dottedToInt(dotted);

  // Cloud-metadata endpoint (most specific): the curated per-provider table.
  // Runs FIRST so an endpoint inside a broader special-use range (169.254.169.254
  // in link-local, 100.100.100.200 in CGNAT, 192.0.0.192 in the IETF protocol
  // assignments block) classifies as metadata, not as the enclosing range. It is
  // a /32 overlay, i.e. the most specific match there is.
  const metadata = METADATA_IPV4.get(n);
  if (metadata !== undefined) return metadataMatch(metadata);

  // Everything else: longest-prefix-match against the IANA table.
  const range = matchIpv4Range(n);
  if (range) return { bucket: range.bucket, rangeName: range.name, rangeRfc: range.rfc };

  // Otherwise an ordinary public IPv4 — no bucket.
  return null;
}

/** Classify a canonical RFC 5952 IPv6 string into exactly one bucket, or null. */
function classifyIpv6(canonical: string): BucketMatch | null {
  const c = canonical.toLowerCase();

  // Cloud-metadata IPv6 endpoint (most specific): the curated per-provider
  // table, keyed by the RFC 5952 canonical form. Both sides of the comparison
  // are parsed and re-rendered, so `fd00:0ec2::254` and `FD00:EC2:0:0:0:0:0:254`
  // match the same row as `fd00:ec2::254` — a text prefix test would not.
  const metadata = METADATA_IPV6.get(c);
  if (metadata !== undefined) return metadataMatch(metadata);

  // Everything else: longest-prefix-match against the IANA table, on the
  // EXPANDED hextets. The old first-hextet test could only express /16-aligned
  // prefixes, so it silently rounded fc00::/7 and fe80::/10 to hextet ranges and
  // could not see a /128 exception inside a /23 at all.
  const hextets = hextetsOf(c);
  if (hextets === null) return null;
  const range = matchIpv6Range(hextets);
  if (range) return { bucket: range.bucket, rangeName: range.name, rangeRfc: range.rfc };

  // Anything else (e.g. 2001:db8::1) is public/unclassified — no bucket.
  return null;
}

const SUMMARY: Record<Bucket, string> = {
  // Bucket-level fallback, used only if a row somehow carries no provider. Kept
  // kind-neutral: the bucket spans instance metadata AND other provider-internal
  // infrastructure, so naming one of them here would re-introduce the very
  // mis-description this file's `endpointKind` exists to prevent.
  ip_cloud_metadata: "a cloud provider-internal endpoint (SSRF target)",
  ip_loopback: "a loopback address",
  ip_link_local: "a link-local address",
  ip_private: "a private (internal) address",
  ip_reserved: "a reserved / special-use address",
};

/** A classified literal-IP host: its range bucket plus display/canonical forms. */
export interface IpClassification {
  bucket: Bucket;
  /** Host as shown in detail strings (IPv6 wrapped in brackets). */
  shown: string;
  /** Canonical address that determined the bucket. */
  canonical: string;
  /**
   * Cloud vendor owning the matched metadata endpoint, from the curated
   * `data/cloud-metadata.ts` table. Present only on `ip_cloud_metadata`; the
   * generic range buckets have no provider.
   */
  provider?: string;
  /**
   * Which flavour of endpoint the matched row is — an IMDS
   * (`"instance-metadata"`) or other vendor platform infrastructure
   * (`"provider-internal"`). Present only on `ip_cloud_metadata`, alongside
   * {@link provider}.
   *
   * Affects the DETAIL WORDING only. The reason code is `ip_cloud_metadata` for
   * both kinds and the weight is identical, so a consumer keying off `code` is
   * unaffected by a row being re-described (LINK-mjbrzxeo).
   */
  endpointKind?: CloudEndpointKind;
  /**
   * IANA registry name of the matched range (`"Private-Use"`, `"Loopback"`, …).
   * Present on every range bucket; absent on `ip_cloud_metadata`, whose table is
   * vendor-documented rather than registry-derived.
   */
  rangeName?: string;
  /**
   * RFC citation of the matched range, verbatim from the registry
   * (`"[RFC1918]"`, `"[RFC1122], Section 3.2.1.3"`). Same presence rule as
   * {@link rangeName}.
   */
  rangeRfc?: string;
  /**
   * The RFC transition wrapper the bucket was read through, when an IPv6
   * literal was classified by the IPv4 in its low 32 bits. Present only on that
   * path, so the reason can explain WHY an IPv6 host produced an IPv4 verdict.
   */
  embeddedVia?: string;
  /**
   * Set when the bucket was decided by a vendor-documented HOSTNAME rather than
   * by an address in the URL (LINK-hvawpgos). {@link canonical} then holds the
   * address the vendor publishes that name for, and the wording must say so:
   * linklint resolved nothing, and a detail that read "resolves to" would be
   * asserting a DNS outcome this library never observed.
   *
   * Never set by {@link classifyHost}, which is IP-only.
   */
  viaHostname?: true;
}

/**
 * Classify a HOSTNAME that a vendor publishes as an address of a metadata
 * endpoint already in `CLOUD_METADATA_ENDPOINTS`, or null for every other host.
 *
 * Exact match on the whole host after case folding and after dropping one
 * trailing root dot — never a suffix, prefix, or substring test. The trailing
 * dot matters: `metadata.google.internal.` is the documented Smokescreen
 * allow-list bypass (see `fqdn-root-label.ts`), resolves identically, and would
 * otherwise walk straight past this table. Two or more trailing dots never
 * arrive — they fail parsing as an empty label.
 *
 * The narrowness IS the detector. `metadata.mycorp.com` and `svc.internal` are
 * ordinary internal-looking names and must stay silent; anything looser than
 * whole-host equality turns a specification index into a blocklist.
 */
export function classifyMetadataHostname(host: string): IpClassification | null {
  const row = matchCloudMetadataHostname(host);
  if (row === undefined) return null;
  return {
    bucket: "ip_cloud_metadata",
    shown: host,
    canonical: row.address,
    provider: row.provider,
    endpointKind: row.kind ?? "instance-metadata",
    viaHostname: true,
  };
}

/**
 * Classify `ctx.host` into exactly one range bucket, or null for a public /
 * non-IP host. Shared by the always-on `ipClassification` detector and the
 * agentMode SSRF escalation so the range logic lives in one place.
 */
export function classifyHost(host: string): IpClassification | null {
  if (host === "") return null;

  const ip4 = analyzeIpv4(host);
  if (ip4) {
    const m = classifyIpv4(ip4.canonical);
    return m ? { ...m, shown: host, canonical: ip4.canonical } : null;
  }

  const ip6 = analyzeIpv6(host);
  if (ip6) {
    // IPv4-in-IPv6 embedding: classify by the embedded IPv4 (SSRF masquerade).
    // `embeddedIpv4` comes from the DECODED BITS, so `[64:ff9b::a9fe:a9fe]` and
    // `[64:ff9b::169.254.169.254]` — the same 128 bits, two spellings — land in
    // the same bucket instead of only the dotted one being caught.
    if (ip6.embeddedIpv4) {
      const m = classifyIpv4(ip6.embeddedIpv4);
      // A wrapper around an ordinary public IPv4 (`::ffff:808:808` → 8.8.8.8)
      // has no v4 bucket. Fall through rather than return: the literal itself
      // may still land in an IPv6 bucket, and a wrapper must never SUPPRESS a
      // verdict the bare address would have earned.
      if (m) {
        const base = { ...m, shown: `[${host}]`, canonical: ip6.embeddedIpv4 };
        return ip6.embeddedIpv4Via === undefined
          ? base
          : { ...base, embeddedVia: ip6.embeddedIpv4Via };
      }
    }
    const m = classifyIpv6(ip6.canonical);
    if (m) return { ...m, shown: `[${host}]`, canonical: ip6.canonical };
  }

  return null;
}

export const ipClassification: Detector = {
  id: "ip_classification",
  layer: "lexical",
  run(ctx): DetectorFinding[] {
    // Name first, then address. The two are disjoint by construction — a
    // hostname parses as neither IPv4 nor IPv6 — so the order is for reading,
    // not for precedence.
    const c = classifyMetadataHostname(ctx.host) ?? classifyHost(ctx.host);
    return c ? [finding(c)] : [];
  },
};

/**
 * Noun phrase for a matched `ip_cloud_metadata` endpoint, shared by the two
 * detectors that describe one so they cannot drift apart.
 *
 * The provider is named so the reader learns WHOSE credentials are at stake,
 * and the noun follows the row's kind: `168.63.129.16` is Azure's WireServer
 * channel, documented separately from the Azure IMDS at `169.254.169.254`, so
 * calling it an instance-metadata endpoint stated something Microsoft's own
 * page contradicts (LINK-mjbrzxeo). Wording only — see
 * {@link IpClassification.endpointKind}.
 */
export function cloudEndpointPhrase(c: IpClassification): string {
  const noun =
    c.endpointKind === "provider-internal"
      ? "provider-internal infrastructure endpoint"
      : "instance-metadata endpoint";
  return c.provider === undefined ? `the cloud ${noun}` : `the ${c.provider} ${noun}`;
}

/**
 * How to refer to the address that decided the bucket, shared by both detectors
 * so the two details cannot drift.
 *
 * For an address in the URL this is just the canonical form. For a
 * vendor-documented hostname it must not read as a resolution result: linklint
 * performed no lookup, so the address is named as what the VENDOR publishes the
 * name for, which is a citation rather than an observation.
 */
export function endpointLocator(c: IpClassification): string {
  return c.viaHostname === true
    ? `the vendor-documented name for ${c.canonical}`
    : c.canonical;
}

/**
 * Bucket wording for the detail string. A matched cloud endpoint gets the
 * provider-and-kind phrase above; every other bucket keeps its generic phrasing.
 */
function summaryFor(c: IpClassification): string {
  if (c.bucket === "ip_cloud_metadata" && c.provider !== undefined) {
    return `${cloudEndpointPhrase(c)} (SSRF target)`;
  }
  return SUMMARY[c.bucket];
}

function finding(c: IpClassification): DetectorFinding {
  // An IPv6 literal that produced an IPv4 verdict must say how it got there,
  // or the reason reads as a non-sequitur ("[64:ff9b::a9fe:a9fe] is the cloud
  // metadata endpoint?"). Naming the wrapper turns it into an explanation.
  const via = c.embeddedVia === undefined ? "" : `, unwrapped from the ${c.embeddedVia}`;
  // Every range bucket cites the registry row it came from, so the verdict is
  // checkable against the RFC that defines the block rather than against a
  // number someone typed into this file.
  const cite =
    c.rangeName === undefined ? "" : ` — IANA ${c.rangeName}, ${c.rangeRfc ?? ""}`.trimEnd();
  // A hostname match takes its own sentence shape. "resolves to" is accurate for
  // an address the URL already carries and FALSE for a name — nothing was
  // resolved, and a zero-network library must not put a DNS claim in its output.
  // The address then trails as a citation rather than sitting in a second
  // parenthetical after the first.
  if (c.viaHostname === true) {
    return {
      code: c.bucket as ReasonCode,
      detail: `host '${c.shown}' is ${summaryFor(c)} — ${endpointLocator(c)}`,
    };
  }
  return {
    code: c.bucket as ReasonCode,
    detail: `host '${c.shown}' resolves to ${summaryFor(c)} (${c.canonical}${via})${cite}`,
  };
}
