import { CONFUSABLES_RAW, CONFUSABLES_VERSION } from "./confusables.generated.js";

/**
 * Confusables lookup, built from the official Unicode UTS#39 confusables table
 * (generated by tools/build-confusables.mjs — do NOT hand-edit the generated
 * file). Maps a confusable character to the ASCII prototype it is visually
 * confusable with, plus the official target name.
 *
 * A target may be a MULTI-codepoint sequence (e.g. ` æ` → `ae`, a "rn"-style
 * lookalike of `m`), so `target` is a string, not a single char.
 *
 * Version: dataVersions.unicodeConfusables = CONFUSABLES_VERSION.
 */
export interface ConfusableTarget {
  /** The ASCII prototype this is confusable with (may be multiple chars). */
  target: string;
  /** Human-readable description, e.g. `"a (U+0061, LATIN SMALL LETTER A)"`. */
  confusableWith: string;
}

function describe(target: string, name: string): string {
  const cps = [...target]
    .map((c) => `U+${c.codePointAt(0)!.toString(16).toUpperCase().padStart(4, "0")}`)
    .join(" ");
  return `${target} (${cps}, ${name})`;
}

/** Lookup table: confusable character → its ASCII prototype + description. */
export const CONFUSABLES: ReadonlyMap<string, ConfusableTarget> = new Map(
  CONFUSABLES_RAW.map(([cp, target, name]) => [
    String.fromCodePoint(cp),
    { target, confusableWith: describe(target, name) },
  ]),
);

export { CONFUSABLES_VERSION };
