import {
  IPV4_SPECIAL_RANGES,
  IPV6_SPECIAL_RANGES,
  IP_RANGES_VERSION,
  type IpRangeBucket,
  type Ipv4RangeRow,
  type Ipv6RangeRow,
} from "./ip-ranges.generated.js";

/**
 * Special-purpose IP range table: the IANA registries (generated by
 * tools/build-ip-ranges.mjs — do NOT hand-edit `ip-ranges.generated.ts`) plus
 * the ONE class of range the registries do not cover, matched by
 * LONGEST-PREFIX-MATCH.
 *
 * Longest-prefix-match is not a stylistic choice: the registry expresses
 * EXCEPTIONS INSIDE a block. `192.0.0.9/32` (PCP anycast) and `192.0.0.10/32`
 * (TURN anycast) are globally reachable carve-outs inside the non-global
 * `192.0.0.0/24`; `2001:1::1/128` is one inside `2001::/23`. A flat first-match
 * range list cannot represent that — it either loses the /24 or loses the /32.
 *
 * Version: dataVersions.ipRanges = IP_RANGES_VERSION.
 */

/** A matched range that earns a bucket, with the registry's own citation. */
export interface IpRangeMatch {
  bucket: IpRangeBucket;
  /** Registry name of the block, e.g. `"Private-Use"`. */
  name: string;
  /** RFC citation carried verbatim from the registry, e.g. `"[RFC1918]"`. */
  rfc: string;
}

/**
 * NON-REGISTRY OVERLAY — multicast.
 *
 * Multicast is NOT in the special-purpose registries: `224.0.0.0/4` and
 * `ff00::/8` are registered in the separate IANA *Multicast Address Space*
 * registries. A purely special-purpose-derived table silently LOSES them, so
 * they are added here explicitly — exactly like the cloud-metadata table
 * (`./cloud-metadata.ts`), the project's other deliberately non-IANA-registry
 * overlay. Both are most-specific-match participants, not special cases.
 */
const MULTICAST_IPV4: Ipv4RangeRow = {
  base: 0xe0000000,
  prefix: 4,
  bucket: "ip_reserved",
  name: "Multicast",
  rfc: "[RFC5771], Section 2",
};
const MULTICAST_IPV6: Ipv6RangeRow = {
  base: [0xff00, 0, 0, 0, 0, 0, 0, 0],
  prefix: 8,
  bucket: "ip_reserved",
  name: "Multicast",
  rfc: "[RFC4291], Section 2.7",
};

/**
 * The full tables, sorted by DESCENDING prefix length so a linear scan returns
 * the most specific match first. With ~26 rows per family a scan is cheaper
 * than any trie and stays readable; the sort runs once at module load.
 */
export const IPV4_RANGES: readonly Ipv4RangeRow[] = [
  ...IPV4_SPECIAL_RANGES,
  MULTICAST_IPV4,
].sort((a, b) => b.prefix - a.prefix);

export const IPV6_RANGES: readonly Ipv6RangeRow[] = [
  ...IPV6_SPECIAL_RANGES,
  MULTICAST_IPV6,
].sort((a, b) => b.prefix - a.prefix);

/**
 * Longest-prefix-match an IPv4 address (uint32) against the table.
 *
 * Returns null both when nothing matches (an ordinary public address) and when
 * the most specific match is a `bucket: null` carve-out — a globally reachable
 * or curated-inert block INSIDE a special-purpose one. The carve-out must stop
 * the search rather than fall through to its parent, which is precisely what
 * longest-prefix-match buys: `192.0.0.9` is ordinary even though `192.0.0.0/24`
 * is reserved.
 */
export function matchIpv4Range(addr: number): IpRangeMatch | null {
  for (const row of IPV4_RANGES) {
    // `prefix` is never 0 in either registry, so the shift is always defined.
    if (((addr ^ row.base) >>> (32 - row.prefix)) !== 0) continue;
    return row.bucket === null ? null : { bucket: row.bucket, name: row.name, rfc: row.rfc };
  }
  return null;
}

/**
 * Longest-prefix-match an IPv6 address (8 hextets) against the table. Same
 * carve-out semantics as {@link matchIpv4Range}.
 *
 * Compared hextet by hextet on 16-bit integers — no BigInt, so the hot path
 * stays inside the perf budget (NFR-PERF-1).
 */
export function matchIpv6Range(hextets: readonly number[]): IpRangeMatch | null {
  if (hextets.length !== 8) return null;
  rows: for (const row of IPV6_RANGES) {
    const whole = row.prefix >> 4;
    for (let i = 0; i < whole; i++) if (hextets[i] !== row.base[i]) continue rows;
    const rest = row.prefix & 15;
    if (rest !== 0) {
      const mask = (0xffff << (16 - rest)) & 0xffff;
      if ((hextets[whole]! & mask) !== row.base[whole]) continue rows;
    }
    return row.bucket === null ? null : { bucket: row.bucket, name: row.name, rfc: row.rfc };
  }
  return null;
}

export { IP_RANGES_VERSION };
export type { IpRangeBucket, Ipv4RangeRow, Ipv6RangeRow };
