// AUTO-GENERATED by tools/build-ip-ranges.mjs — DO NOT EDIT.
// Regenerate with: pnpm data:ip-ranges  (node tools/build-ip-ranges.mjs)
//
// Sources (IANA Special-Purpose Address Registries, snapshot 2026-07-25):
//   https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry-1.csv
//   sha256: e4a1c06ecf8e934ed5ae30977a1477a78957da1a5fb602fc855e3f74bf01c8ac  (2397 bytes, 26 ranges, 18 bucketed)
//   https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry-1.csv
//   sha256: 8b0e181a4ef0c71fcb25403c40702f2050c2f6dc198156b6ec1a5fb746c9a73e  (2263 bytes, 25 ranges, 10 bucketed)
//
// The parsed snapshots are committed at tools/data/*.csv, so this file is
// byte-reproducible offline; ip-ranges.test.ts runs the --check drift guard.
//
// The digests above are taken over the COMMITTED snapshots, which are
// LF-normalized. IANA serves these files with CRLF row terminators, so a fresh
// download hashes differently — convert with `tr -d '\r'` (or equivalent) before
// comparing. Normalizing is deliberate: this repo is LF-only (.gitattributes,
// plus a mixed-line-ending pre-commit hook whose --fix=auto would otherwise
// rewrite the LF newlines that appear INSIDE quoted CSV fields, corrupting the
// data). Row counts are identical either way.
//
// License: IANA registry data is public domain (no restrictions on reuse).
//
// Rows are sorted by DESCENDING prefix length: a linear scan returns the
// longest-prefix (most specific) match first. `bucket: null` is a real,
// load-bearing entry — a globally-reachable or curated-inert carve-out INSIDE a
// broader special-purpose block (192.0.0.9/32 inside 192.0.0.0/24, 2001::/32
// inside 2001::/23). See tools/build-ip-ranges.mjs for the bucket mapping.
//
// NOT INCLUDED: multicast (224.0.0.0/4, ff00::/8) is registered in the separate
// IANA Multicast Address Space registries; it is overlaid in ./ip-ranges.ts.

/** Version id stamped into dataVersions.ipRanges. */
export const IP_RANGES_VERSION = "iana-special-purpose-2026-07-25";

/** Range buckets a special-purpose block can map to (metadata is not one). */
export type IpRangeBucket = "ip_loopback" | "ip_link_local" | "ip_private" | "ip_reserved";

/** One IPv4 range. `base` is the network address as a uint32. */
export interface Ipv4RangeRow {
  readonly base: number;
  readonly prefix: number;
  /** null = matches, but earns NO bucket (carve-out). */
  readonly bucket: IpRangeBucket | null;
  readonly name: string;
  /** RFC citation, carried verbatim from the registry into the reason detail. */
  readonly rfc: string;
}

/** One IPv6 range. `base` is the network address as 8 hextets. */
export interface Ipv6RangeRow {
  readonly base: readonly number[];
  readonly prefix: number;
  /** null = matches, but earns NO bucket (carve-out). */
  readonly bucket: IpRangeBucket | null;
  readonly name: string;
  /** RFC citation, carried verbatim from the registry into the reason detail. */
  readonly rfc: string;
}

export const IPV4_SPECIAL_RANGES: readonly Ipv4RangeRow[] = [
  { base: 0x00000000, prefix: 32, bucket: "ip_reserved", name: "\"This host on this network\"", rfc: "[RFC1122], Section 3.2.1.3" }, // 0.0.0.0/32
  { base: 0xc0000008, prefix: 32, bucket: "ip_reserved", name: "IPv4 dummy address", rfc: "[RFC7600]" }, // 192.0.0.8/32
  { base: 0xc0000009, prefix: 32, bucket: null, name: "Port Control Protocol Anycast", rfc: "[RFC7723]" }, // 192.0.0.9/32 — globally reachable
  { base: 0xc000000a, prefix: 32, bucket: null, name: "Traversal Using Relays around NAT Anycast", rfc: "[RFC8155]" }, // 192.0.0.10/32 — globally reachable
  { base: 0xc00000aa, prefix: 32, bucket: "ip_reserved", name: "NAT64/DNS64 Discovery", rfc: "[RFC8880][RFC7050], Section 2.2" }, // 192.0.0.170/32
  { base: 0xc00000ab, prefix: 32, bucket: "ip_reserved", name: "NAT64/DNS64 Discovery", rfc: "[RFC8880][RFC7050], Section 2.2" }, // 192.0.0.171/32
  { base: 0xc0586302, prefix: 32, bucket: "ip_reserved", name: "6a44-relay anycast address", rfc: "[RFC6751]" }, // 192.88.99.2/32
  { base: 0xffffffff, prefix: 32, bucket: "ip_reserved", name: "Limited Broadcast", rfc: "[RFC8190] [RFC919], Section 7" }, // 255.255.255.255/32
  { base: 0xc0000000, prefix: 29, bucket: "ip_reserved", name: "IPv4 Service Continuity Prefix", rfc: "[RFC7335]" }, // 192.0.0.0/29
  { base: 0xc0000000, prefix: 24, bucket: "ip_reserved", name: "IETF Protocol Assignments", rfc: "[RFC6890], Section 2.1" }, // 192.0.0.0/24
  { base: 0xc0000200, prefix: 24, bucket: null, name: "Documentation (TEST-NET-1)", rfc: "[RFC5737]" }, // 192.0.2.0/24 — curated: documentation, inert
  { base: 0xc01fc400, prefix: 24, bucket: null, name: "AS112-v4", rfc: "[RFC7535]" }, // 192.31.196.0/24 — globally reachable
  { base: 0xc034c100, prefix: 24, bucket: null, name: "AMT", rfc: "[RFC7450]" }, // 192.52.193.0/24 — globally reachable
  { base: 0xc0586300, prefix: 24, bucket: "ip_reserved", name: "Deprecated (6to4 Relay Anycast)", rfc: "[RFC7526]" }, // 192.88.99.0/24
  { base: 0xc0af3000, prefix: 24, bucket: null, name: "Direct Delegation AS112 Service", rfc: "[RFC7534]" }, // 192.175.48.0/24 — globally reachable
  { base: 0xc6336400, prefix: 24, bucket: null, name: "Documentation (TEST-NET-2)", rfc: "[RFC5737]" }, // 198.51.100.0/24 — curated: documentation, inert
  { base: 0xcb007100, prefix: 24, bucket: null, name: "Documentation (TEST-NET-3)", rfc: "[RFC5737]" }, // 203.0.113.0/24 — curated: documentation, inert
  { base: 0xa9fe0000, prefix: 16, bucket: "ip_link_local", name: "Link Local", rfc: "[RFC3927]" }, // 169.254.0.0/16
  { base: 0xc0a80000, prefix: 16, bucket: "ip_private", name: "Private-Use", rfc: "[RFC1918]" }, // 192.168.0.0/16
  { base: 0xc6120000, prefix: 15, bucket: "ip_reserved", name: "Benchmarking", rfc: "[RFC2544]" }, // 198.18.0.0/15
  { base: 0xac100000, prefix: 12, bucket: "ip_private", name: "Private-Use", rfc: "[RFC1918]" }, // 172.16.0.0/12
  { base: 0x64400000, prefix: 10, bucket: "ip_reserved", name: "Shared Address Space", rfc: "[RFC6598]" }, // 100.64.0.0/10
  { base: 0x00000000, prefix: 8, bucket: "ip_reserved", name: "\"This network\"", rfc: "[RFC791], Section 3.2" }, // 0.0.0.0/8
  { base: 0x0a000000, prefix: 8, bucket: "ip_private", name: "Private-Use", rfc: "[RFC1918]" }, // 10.0.0.0/8
  { base: 0x7f000000, prefix: 8, bucket: "ip_loopback", name: "Loopback", rfc: "[RFC1122], Section 3.2.1.3" }, // 127.0.0.0/8
  { base: 0xf0000000, prefix: 4, bucket: "ip_reserved", name: "Reserved", rfc: "[RFC1112], Section 4" }, // 240.0.0.0/4
];

export const IPV6_SPECIAL_RANGES: readonly Ipv6RangeRow[] = [
  { base: [0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 128, bucket: "ip_reserved", name: "Unspecified Address", rfc: "[RFC4291]" }, // ::/128
  { base: [0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1], prefix: 128, bucket: "ip_loopback", name: "Loopback Address", rfc: "[RFC4291]" }, // ::1/128
  { base: [0x2001, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1], prefix: 128, bucket: null, name: "Port Control Protocol Anycast", rfc: "[RFC7723]" }, // 2001:1::1/128 — globally reachable
  { base: [0x2001, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2], prefix: 128, bucket: null, name: "Traversal Using Relays around NAT Anycast", rfc: "[RFC8155]" }, // 2001:1::2/128 — globally reachable
  { base: [0x2001, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3], prefix: 128, bucket: null, name: "DNS-SD Service Registration Protocol Anycast", rfc: "[RFC9665]" }, // 2001:1::3/128 — globally reachable
  { base: [0x0, 0x0, 0x0, 0x0, 0x0, 0xffff, 0x0, 0x0], prefix: 96, bucket: null, name: "IPv4-mapped Address", rfc: "[RFC4291]" }, // ::ffff:0:0/96 — curated: transition wrapper
  { base: [0x64, 0xff9b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 96, bucket: null, name: "IPv4-IPv6 Translat.", rfc: "[RFC6052]" }, // 64:ff9b::/96 — curated: transition wrapper
  { base: [0x100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 64, bucket: "ip_reserved", name: "Discard-Only Address Block", rfc: "[RFC6666]" }, // 100::/64
  { base: [0x100, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0], prefix: 64, bucket: "ip_reserved", name: "Dummy IPv6 Prefix", rfc: "[RFC9780]" }, // 100:0:0:1::/64
  { base: [0x64, 0xff9b, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 48, bucket: null, name: "IPv4-IPv6 Translat.", rfc: "[RFC8215]" }, // 64:ff9b:1::/48 — curated: transition wrapper
  { base: [0x2001, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 48, bucket: "ip_reserved", name: "Benchmarking", rfc: "[RFC5180][RFC Errata 1752]" }, // 2001:2::/48
  { base: [0x2001, 0x4, 0x112, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 48, bucket: null, name: "AS112-v6", rfc: "[RFC7535]" }, // 2001:4:112::/48 — globally reachable
  { base: [0x2620, 0x4f, 0x8000, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 48, bucket: null, name: "Direct Delegation AS112 Service", rfc: "[RFC7534]" }, // 2620:4f:8000::/48 — globally reachable
  { base: [0x2001, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 32, bucket: null, name: "TEREDO", rfc: "[RFC4380] [RFC8190]" }, // 2001::/32 — curated: transition wrapper
  { base: [0x2001, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 32, bucket: null, name: "AMT", rfc: "[RFC7450]" }, // 2001:3::/32 — globally reachable
  { base: [0x2001, 0xdb8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 32, bucket: null, name: "Documentation", rfc: "[RFC3849]" }, // 2001:db8::/32 — curated: documentation, inert
  { base: [0x2001, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 28, bucket: "ip_reserved", name: "Deprecated (previously ORCHID)", rfc: "[RFC4843]" }, // 2001:10::/28
  { base: [0x2001, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 28, bucket: null, name: "ORCHIDv2", rfc: "[RFC7343]" }, // 2001:20::/28 — globally reachable
  { base: [0x2001, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 28, bucket: null, name: "Drone Remote ID Protocol Entity Tags (DETs) Prefix", rfc: "[RFC9374]" }, // 2001:30::/28 — globally reachable
  { base: [0x2001, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 23, bucket: "ip_reserved", name: "IETF Protocol Assignments", rfc: "[RFC2928]" }, // 2001::/23
  { base: [0x3fff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 20, bucket: null, name: "Documentation", rfc: "[RFC9637]" }, // 3fff::/20 — curated: documentation, inert
  { base: [0x2002, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 16, bucket: null, name: "6to4", rfc: "[RFC3056]" }, // 2002::/16 — curated: transition wrapper
  { base: [0x5f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 16, bucket: "ip_reserved", name: "Segment Routing (SRv6) SIDs", rfc: "[RFC9602]" }, // 5f00::/16
  { base: [0xfe80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 10, bucket: "ip_link_local", name: "Link-Local Unicast", rfc: "[RFC4291]" }, // fe80::/10
  { base: [0xfc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0], prefix: 7, bucket: "ip_private", name: "Unique-Local", rfc: "[RFC4193] [RFC8190]" }, // fc00::/7
];
